nodeshift/nodejs-reference-architecture

- auth.md
Make fixes reported within internal repo by @David-Sint.
> doc: make fixes reported earlier

- .github/workflows/style.yml
- .gitignore
- CONTRIBUTING.md
- README.md
- docs/development/code-consistency.md
- docs/functional-components/auth.md
- docs/functional-components/internationalization.md
- docs/functional-components/message-queuing.md
- docs/functional-components/template-engines.md
- docs/functional-components/webframework.md
- docs/operations/failurehandling.md
- docs/operations/healthchecks.md
- docs/operations/logging.md
- docs/operations/metrics.md
- package.json
Detect markdown issues and style issues on PR level by adding github actions capability.
This can be extended later to include extra styling for website etc.
This resolves first part of the #21
> Add style checks to the repository by enforcing proper formatting and standards.

- README.md
- docs/functional-components/data-caching.md
- modules-list.json
- add caching section based on team discussion
> doc: add caching section

- .github/workflows/style.yml
- .gitignore
- CONTRIBUTING.md
- README.md
- docs/development/code-consistency.md
- docs/functional-components/auth.md
- docs/functional-components/data-caching.md
- docs/functional-components/internationalization.md
- docs/functional-components/message-queuing.md
- docs/functional-components/template-engines.md
- docs/functional-components/webframework.md
- docs/operations/failurehandling.md
- docs/operations/healthchecks.md
- docs/operations/logging.md
- docs/operations/metrics.md
- package.json
Detect markdown issues and style issues on PR level by adding github actions capability.
This can be extended later to include extra styling for website etc.
This resolves first part of the #21
> Github actions and style checks

- README.md
- docs/functional-components/multi-threading.md
- docs/functional-components/scaling-multi-threading.md
> doc: add multi-threading section

- docs/operations/logging.md
Add additional best logging practices used by some of the IBM Blockchain development teams.
> Add additional best logging practices

- docs/functional-components/webframework.md
> doc: Add guidance on http headers in web framework section

- README.md
> doc: add reference to blog post series

- README.md
> doc: add contributors section

- docs/functional-components/internationalization.md
- npcheck.json
Update recommendations to reflect deprecated components
> doc: update recommendations for i18n

- docs/functional-components/message-queuing.md
- npcheck.json
This is the update that I'm suggesting after discussion with the IBM and RH
messaging teams.
> Update kafka recommendations

- docs/intro.md
In the website repo add the link to the github repo so that it is easy to find from the generated website.
> Add link to github repo

- docs/development/typescript.md
First draft of typescript article, still some TODOs
> Initial draft of typescript guide

- README.md
- docs/development/dependencies.md
> doc: initial version of dependencies section

- npcheck-review/npcheck-dec6-2021.md
- npcheck.json
> doc: add npcheck review for Dec 2021

- npcheck.json
- requires https://github.com/nodeshift/npcheck/pull/133
to land in order to take effect
> test: exclude vulnerability that is ok to ignore

- README.md
- docs/development/protecting-code.md
> doc: add section on protection code

- docs/functional-components/rest-api-development.md
- npcheck.json
Refs: https://github.com/nodeshift/nodejs-reference-architecture/issues/73
> doc: udpate for recent suggestions

- npcheck-review/npcheck-march19-2022.md
> doc: add npcheck review for March 19 review

- README.md
- docs/operations/problem-determination.md
> doc: initial version of problem determination section

- README.md
- docs/development/accessibility.md
> doc: first cut at accessiblity section

- README.md
Updated the table of contents based on the review today in the Ref arch meeting.
> Updated table of contents based on review

- npcheck-review/npcheck-july7-2022.md
> doc: add 2022 Q2 npcheck review

- README.md
- docs/functional-components/consuming-services.md
- npcheck.json
> doc: add consuming services section

- docs/operations/distributed-tracing.md
- npcheck.json
This commit also:
* Fixes 404 getting started link
> chore: OpenTelemetry package addition

- npcheck-review/npcheck-oct20-2022.md
> feat: add npcheck review on Ref arch for Q3 2022

- README.md
- docs/development/dev-flows.md
> doc: initial draft of dev workflows section

- npcheck-review/npcheck-jan4-2023.md
> doc: add npcheck Q4 review

- README.md
- docs/functional-components/transaction-handling.md
> doc: initial cut at transaction handling section

- README.md
- docs/development/npm-package-development.md
All Sections should be complete.  I've left the ESM/CJS section as TBD since we are still talking about this section in various chat rooms
> feat: add npm development section.

- README.md
- docs/functional-components/scaling-multi-threading.md
It looks like we have already covered what we
have to say about load balancing in the existing
section
> doc: fold load balancing into scaling/threading

- README.md
- docs/development/ci-cd.md
> doc: initial version of ci/cd section

- npcheck.json
- Another user of 0BSD which we decided before is ok as an exception.
> Fix new errors reported

- docs/functional-components/webframework.md
Found a simple yet annoying typo and wanted to be of help :)
> chore: fixing typo in webframework.md

- docs/operations/metrics.md
Being the name of a software, I thought it would be better to put it in uppercase.
> chore: uppercasing Prometheus

- docs/development/accessibility.md
- docs/development/building-good-containers.md
- docs/development/ci-cd.md
- docs/development/code-coverage.md
- docs/development/cross-origin.md
- docs/development/dependencies.md
- docs/development/dev-flows.md
- docs/development/kubernetes-dev-environment.md
- docs/development/mono-repository.md
- docs/development/npm-package-development.md
- docs/development/npm-proxy.md
- docs/development/npm-publishing.md
- docs/development/protecting-code.md
- docs/development/secure-development-process.md
- docs/development/serverless.md
- docs/development/testing.md
There were many typos and grammar issues and I decided to do a full run hoping to be of help :)
> chore: multiple grammar or wording fixes

- npcheck-review/npcheck-january29-2025.md
Not much change between Q3 and Q4.
> chore: add npcheck Q4 review
